# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
[
  {
    goPackagePath = "github.com/Sirupsen/logrus";
    fetch = {
      type = "git";
      url = "https://github.com/Sirupsen/logrus";
      rev = "ba0a156bcce961208891f7425e15affae0d39358";
      sha256 = "0pirdhnlrc3prg6nj24aszksygpkwqz5n76xzm85klw41kgma06r";
    };
  }
  {
    goPackagePath = "github.com/bitly/go-simplejson";
    fetch = {
      type = "git";
      url = "https://github.com/bitly/go-simplejson";
      rev = "9db4a59bd4d803ae0c173a7d8a538e056cd59d57";
      sha256 = "0cbnjzjq55jnzk07zdk7nb96yzgpyawm1r6km3xignn8ih4bnn6g";
    };
  }
  {
    goPackagePath = "github.com/eclipse/paho.mqtt.golang";
    fetch = {
      type = "git";
      url = "https://github.com/eclipse/paho.mqtt.golang";
      rev = "20337d8c394721c308cc6ec096990ee451a7cd7f";
      sha256 = "107i0rz8343d602kyzl0ssxzr5qpqzdxr291kcqij2x2pw7qc86i";
    };
  }
  {
    goPackagePath = "github.com/mattn/go-colorable";
    fetch = {
      type = "git";
      url = "https://github.com/mattn/go-colorable";
      rev = "3a70a971f94a22f2fa562ffcc7a0eb45f5daf045";
      sha256 = "0l640974j804c1yyjfgyxqlsivz0yrzmbql4mhcw2azryigkp08p";
    };
  }
  {
    goPackagePath = "github.com/mattn/go-isatty";
    fetch = {
      type = "git";
      url = "https://github.com/mattn/go-isatty";
      rev = "c2a7a6ca930a4cd0bc33a3f298eb71960732a3a7";
      sha256 = "1i77aq4gf9as03m8fpfh8fq49n4z9j7548blrcsidm1xhslzk5xd";
    };
  }
  {
    goPackagePath = "github.com/urfave/cli";
    fetch = {
      type = "git";
      url = "https://github.com/urfave/cli";
      rev = "693af58b4d51b8fcc7f9d89576da170765980581";
      sha256 = "1krq752xgy658an1696vf4dc2zmp541clwjinhn11394sx2qksh6";
    };
  }
  {
    goPackagePath = "golang.org/x/net";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/net";
      rev = "74de082e2cca95839e88aa0aeee5aadf6ce7710f";
      sha256 = "0a4y3y0q5bkif7wvdkyjkvgnzlbh2n4zk7wsy5j95raf0i3zlw4s";
    };
  }
  {
    goPackagePath = "golang.org/x/sys";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/sys";
      rev = "baf5eb976a8cd65845293cd814ea151018552292";
      sha256 = "0bzhw2p352fas017ghhnyg8i0hp1x227h14grqf2nlycgpk2flfb";
    };
  }
]
